# 2022-06-09
# Config file for DCGAN
# Feel free to put local changes here.

VERBOSE: True
VIZUALISE: False
DEBUG: True
LOAD: False
EXP_NAME: "DCGANProgressive_0.1"
SEED: 69
NZ: 100 # length of latent vector
FIG_SIZE: [10, 5]

PATHS:
  DATASET: "../../lsun-dataset"
  MODELS: "./models"
  GRAPHS: "./graphs"

TRAIN:
  WORKERS: 16
  BATCH_SIZE: 1024
  SHUFFLE: True
  NUM_EPOCHS: 2
  DEVICE: "cuda:0"
  NGPU: 1
  CRITERION:
    type: torch.nn.BCELoss

OPTIMIZER_G_NAME: Adam # to choose: Adadelta, Adam
OPTIMIZER_D_NAME: Adam # to choose: Adadelta, Adam

# optimizers
ADADELTA:
  LR: 0.0001
  RHO: 0.95
  EPS: 0.0000007
  WEIGHT_DECAY: 0

ADAM:
  LR: 0.000002
  BETA1: 0.5

MODEL_NAME: "DCGANProgressive" # to choose: DCGAN, VAE, ...todo
DCGAN:
  ARCHITECTURE:
    NC: 3 # number of color channels in the input images. For color images this is 3
    NGF: 64 # relates to the depth of feature maps carried through the generator
    NDF: 16 # sets the depth of feature maps propagated through the discriminator
  ACTIVATION: "sigmoid"
  LOSS:
    type: segmentation_models_pytorch.utils.losses.DiceLoss
  METRICS:
    type: segmentation_models_pytorch.utils.metrics.IoU
    threshold: 0.5
  SCHEDULER:
    type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 1
    T_mult: 2
    eta_min: 5e-5
  MODE: "all_the_time"
  PROGRESSIVE_STEP: 2
